
import '../models/recipe.dart';

final List<Recipe> sampleRecipes = [
  Recipe(
    id: '1',
    title: 'Chicken Tikka Masala',
    category: 'Dinner',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600',
    rating: 4.6,
    cookTime: 45,
    difficulty: 'Medium',
    isFavorite: false,
    ingredients: [
      Ingredient(name: 'Chicken breast', quantity: '500g'),
      Ingredient(name: 'Plain yogurt', quantity: '1 cup'),
      Ingredient(name: 'Garam masala', quantity: '1 tsp'),
      Ingredient(name: 'Cumin powder', quantity: '1 tsp'),
      Ingredient(name: 'Coriander powder', quantity: '1 tsp'),
      Ingredient(name: 'Tomato puree', quantity: '1 cup'),
      Ingredient(name: 'Fresh ginger', quantity: '1 inch'),
      Ingredient(name: 'Vegetable oil', quantity: '2 tbsp'),
      Ingredient(name: 'Salt', quantity: 'to taste'),
    ],
    steps: [
      'Cut chicken breast into bite-sized cubes and marinate with yogurt, half of garam masala, salt, and a pinch of turmeric for at least 30 minutes.',
      'Heat oil in a large pan over medium-high heat. Add marinated chicken and cook until golden brown, about 8-10 minutes.',
      'Remove chicken from pan and set aside. In the same pan, add diced onion and cook until softened, about 5 minutes.',
      'Add minced garlic and ginger, cook for another minute until fragrant.',
      'Add remaining garam masala, cumin, and coriander powder. Cook for 30 seconds until aromatic.',
      'Pour in tomato puree and simmer for 10 minutes, stirring occasionally, until sauce thickens.',
      'Stir in heavy cream and return chicken to the pan. Simmer for 5 minutes to heat through.',
      'Garnish with fresh coriander and serve hot with naan or rice.',
    ],
  ),

  Recipe(
    id: '2',
    title: 'Veggie Omelette',
    category: 'Breakfast',
    imageUrl: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=600',
    rating: 4.2,
    cookTime: 12,
    difficulty: 'Easy',
    isFavorite: false,
    ingredients: [
      Ingredient(name: 'Eggs', quantity: '3'),
      Ingredient(name: 'Bell pepper', quantity: '1/2'),
      Ingredient(name: 'Onion', quantity: '1 small'),
      Ingredient(name: 'Butter', quantity: '1 tbsp'),
      Ingredient(name: 'Salt & pepper', quantity: 'to taste'),
    ],
    steps: [
      'Beat eggs in a bowl with salt and pepper.',
      'Chop bell pepper and onion finely.',
      'Melt butter in a non-stick pan over medium heat.',
      'Pour in eggs and let them set slightly, then add vegetables.',
      'Fold omelette in half and serve immediately.',
    ],
  ),

  Recipe(
    id: '3',
    title: 'Caesar Salad',
    category: 'Lunch',
    imageUrl: 'https://images.unsplash.com/photo-1512852939750-1305098529bf?w=600',
    rating: 4.1,
    cookTime: 10,
    difficulty: 'Easy',
    isFavorite: true,
    ingredients: [
      Ingredient(name: 'Romaine lettuce', quantity: '1 head'),
      Ingredient(name: 'Parmesan cheese', quantity: '50g'),
      Ingredient(name: 'Croutons', quantity: '1 cup'),
      Ingredient(name: 'Caesar dressing', quantity: '3 tbsp'),
    ],
    steps: [
      'Wash and chop romaine lettuce.',
      'Toss with Caesar dressing until coated.',
      'Add croutons and shaved parmesan on top.',
      'Serve immediately.',
    ],
  ),

  Recipe(
    id: '4',
    title: 'Chocolate Mousse',
    category: 'Dessert',
    imageUrl: 'https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=600',
    rating: 4.7,
    cookTime: 25,
    difficulty: 'Medium',
    isFavorite: true,
    ingredients: [
      Ingredient(name: 'Dark chocolate', quantity: '200g'),
      Ingredient(name: 'Heavy cream', quantity: '300ml'),
      Ingredient(name: 'Eggs', quantity: '3'),
      Ingredient(name: 'Sugar', quantity: '50g'),
    ],
    steps: [
      'Melt chocolate in a double boiler and let cool slightly.',
      'Whip cream to soft peaks.',
      'Separate eggs. Beat yolks with sugar until pale.',
      'Fold chocolate into yolk mixture.',
      'Fold in whipped cream gently.',
      'Chill for at least 2 hours before serving.',
    ],
  ),

  Recipe(
    id: '5',
    title: 'Beef Karahi',
    category: 'Dinner',
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600',
    rating: 4.8,
    cookTime: 60,
    difficulty: 'Hard',
    isFavorite: true,
    ingredients: [
      Ingredient(name: 'Beef', quantity: '500g'),
      Ingredient(name: 'Tomatoes', quantity: '4 large'),
      Ingredient(name: 'Ginger', quantity: '2 inch'),
      Ingredient(name: 'Green chilies', quantity: '4-5'),
      Ingredient(name: 'Oil', quantity: '4 tbsp'),
      Ingredient(name: 'Salt', quantity: 'to taste'),
    ],
    steps: [
      'Heat oil in a karahi/wok over high heat.',
      'Add beef and cook until browned on all sides.',
      'Add chopped tomatoes and cook until they break down.',
      'Add ginger and green chilies.',
      'Cover and cook on low heat for 30-40 minutes until tender.',
      'Dry out any excess water on high heat.',
      'Garnish with ginger julienne and serve.',
    ],
  ),

  Recipe(
    id: '6',
    title: 'Pancakes',
    category: 'Breakfast',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600',
    rating: 4.4,
    cookTime: 20,
    difficulty: 'Easy',
    isFavorite: true,
    ingredients: [
      Ingredient(name: 'Flour', quantity: '1 cup'),
      Ingredient(name: 'Milk', quantity: '3/4 cup'),
      Ingredient(name: 'Egg', quantity: '1'),
      Ingredient(name: 'Baking powder', quantity: '1 tsp'),
      Ingredient(name: 'Butter', quantity: '2 tbsp'),
      Ingredient(name: 'Sugar', quantity: '1 tbsp'),
    ],
    steps: [
      'Mix dry ingredients: flour, baking powder, sugar.',
      'Whisk wet ingredients: milk, egg, melted butter.',
      'Combine wet and dry — do not overmix.',
      'Pour 1/4 cup batter onto a hot greased pan.',
      'Flip when bubbles form on top. Cook 1 more minute.',
      'Serve with maple syrup.',
    ],
  ),

  Recipe(
    id: '7',
    title: 'Avocado Toast',
    category: 'Breakfast',
    imageUrl: 'https://images.unsplash.com/photo-1603046891745-c8b8e7b89f7a?w=600',
    rating: 4.3,
    cookTime: 8,
    difficulty: 'Easy',
    isFavorite: false,
    ingredients: [
      Ingredient(name: 'Bread slices', quantity: '2'),
      Ingredient(name: 'Avocado', quantity: '1 ripe'),
      Ingredient(name: 'Lemon juice', quantity: '1 tsp'),
      Ingredient(name: 'Red chili flakes', quantity: 'pinch'),
      Ingredient(name: 'Salt', quantity: 'to taste'),
    ],
    steps: [
      'Toast bread until golden and crisp.',
      'Mash avocado with lemon juice and salt.',
      'Spread onto toast.',
      'Top with chili flakes and serve.',
    ],
  ),

  Recipe(
    id: '8',
    title: 'Grilled Salmon',
    category: 'Lunch',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600',
    rating: 4.5,
    cookTime: 20,
    difficulty: 'Medium',
    isFavorite: false,
    ingredients: [
      Ingredient(name: 'Salmon fillet', quantity: '200g'),
      Ingredient(name: 'Olive oil', quantity: '2 tbsp'),
      Ingredient(name: 'Garlic', quantity: '2 cloves'),
      Ingredient(name: 'Lemon', quantity: '1'),
      Ingredient(name: 'Fresh herbs', quantity: 'handful'),
    ],
    steps: [
      'Marinate salmon with olive oil, garlic, lemon juice for 15 minutes.',
      'Preheat grill to medium-high.',
      'Grill salmon 4-5 minutes per side.',
      'Garnish with fresh herbs and lemon slices.',
    ],
  ),
];